name: Clojure Format & Test & Lint

on: [push]

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@main
        with:
          cli: 'latest'

      - name: Setup clojure-lsp
        uses: clojure-lsp/setup-clojure-lsp@v1
        with:
          clojure-lsp-version: 2024.08.05-18.16.00

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          # key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          # key: cljdeps-${{ hashFiles('project.clj') }}
          # key: cljdeps-${{ hashFiles('build.boot') }}
          restore-keys: cljdeps-

      - name: Check formatting of source code (cljfmt)
        run: clojure-lsp format

      - name: Check formatting of namespace form
        run: clojure-lsp clean-ns --dry

      - name: Run tests
        run: clj -X:test

      - name: Run linter (clj-kondo)
        run: clojure-lsp diagnostics